### ISSUE TITLE
Annotated test datasets?

### ISSUE THREAD

**Issue by glebm** [nlpub/russe-wsi-kit#3]
Are the annotated tests datasets available? Where are they published?

**Comment by lopuhin** [comment]
@glebm they are not available yet, but we already made a decision to make them public and they should be in this repo soon - sorry for the delay. I'll post in this issue once they are available.

**Comment by glebm** [comment]
Thank you!

**Comment by OlzhaskK** [comment]
Above it was announced that the annotated tests datasets would be available. Could you inform where they were published? Thank you.

**Comment by alexanderpanchenko** [comment]
Now test data are available. You can also submit to the post-competition to get the evaluation on these datasets.
